### ISSUE TITLE
error on installation if cypress folder is not found

### ISSUE THREAD

**Issue by maku** [bahmutov/add-typescript-to-cypress#3]
- version 1.1.0
- platform macOS 10.13.2

I get an error on installation
```
> @bahmutov/add-typescript-to-cypress@1.1.0 postinstall /Users/martin/_dev/angular/cypress/cypress-test/node_modules/@bahmutov/add-typescript-to-cypress
> node src/add-plugin.js

adding TypeScript plugin to Cypress
current folder /Users/martin/_dev/angular/cypress/cypress-test/node_modules/@bahmutov/add-typescript-to-cypress
cp /Users/martin/_dev/angular/cypress/cypress-test/node_modules/@bahmutov/add-typescript-to-cypress/src/plugin.js /Users/martin/_dev/angular/cypress/cypress-test/cypress/plugins/index.js
/Users/martin/_dev/angular/cypress/cypress-test/node_modules/shelljs/src/common.js:417
      if (config.fatal) throw e;
                        ^

Error: cp: copyFileSync: could not write to dest file (code=ENOENT):/Users/martin/_dev/angular/cypress/cypress-test/cypress/plugins/index.js
    at Object.error (/Users/martin/_dev/angular/cypress/cypress-test/node_modules/shelljs/src/common.js:128:27)
    at copyFileSync (/Users/martin/_dev/angular/cypress/cypress-test/node_modules/shelljs/src/cp.js:66:14)
    at /Users/martin/_dev/angular/cypress/cypress-test/node_modules/shelljs/src/cp.js:293:7
    at Array.forEach (<anonymous>)
    at Object._cp (/Users/martin/_dev/angular/cypress/cypress-test/node_modules/shelljs/src/cp.js:238:11)
    at Object.cp (/Users/martin/_dev/angular/cypress/cypress-test/node_modules/shelljs/src/common.js:399:25)
    at addPluginFile (/Users/martin/_dev/angular/cypress/cypress-test/node_modules/@bahmutov/add-typescript-to-cypress/src/add-plugin.js:22:11)
    at Object.<anonymous> (/Users/martin/_dev/angular/cypress/cypress-test/node_modules/@bahmutov/add-typescript-to-cypress/src/add-plugin.js:39:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @bahmutov/add-typescript-to-cypress@1.1.0 postinstall: `node src/add-plugin.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @bahmutov/add-typescript-to-cypress@1.1.0 postinstall script.

```

**Comment by bahmutov** [comment]
Hmm, did you scaffold the `cypress` folder before running this? It probably just fails to find folder `cypress/plugins` - it should give a better message of course

**Comment by bahmutov** [comment]
Version `1.1.1` has been published to NPM. The full release note can be found at [add-typescript-to-cypress/releases/tag/v1.1.1](https://github.com/bahmutov/add-typescript-to-cypress/releases/tag/v1.1.1).

**Tip:** safely upgrade dependency @bahmutov/add-typescript-to-cypress in your project using [next-update](https://github.com/bahmutov/next-update)
